djangobrief/urls.py
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.contrib.sitemaps.views import index # для индексного sitemap
from django.contrib.sitemaps import Sitemap
from models.models import Entry

from django.urls import path, include, reverse


# для media files
from django.conf.urls.static import static
from django.conf import settings
# для media files конец

from django.http import HttpResponse

# from django.contrib.flatpages import views

handler403 = 'template.views.response_error_handler'
handler404 = lambda request, exception: HttpResponse('привет. я handler404 in urls.py')


class BlogSitemap(Sitemap):
    changefreq = "never"
    priority = 0.5

    def items(self):
        return Entry.objects.all()

    def lastmod(self, obj):
        return obj.pub_date


class StaticSitemap(Sitemap):
    changefreq = 'never'
    priority = 0.6

    def items(self):
        return ['request:index', 'models:index']

    def location(self, obj):
        return reverse(obj)


sitemaps = {
    'entry': BlogSitemap,
    'static': StaticSitemap,
}

urlpatterns = [
    path('sitemap.xml', index, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.index'),
    path('sitemap-<section>.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('request/', include('request.urls')),
    path('forms/', include('forms.urls')),
    path('models/', include('models.urls')),
    path('template/', include('template.urls')),
    path('views/', include('views.urls')),
    path('myauth/', include('myauth.urls')),
    path('tools/', include('tools.urls')),
    path('admin/', admin.site.urls),
]

# для отображения media files
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += [
    path('', include('django.contrib.flatpages.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

forms/urls.py
from django.urls import path
from . import views


app_name = 'forms'

urlpatterns = [
    path('usualforms/', views.usualforms, name='usualforms'),
    path('modelforms/', views.modelforms, name="modelforms"),
    path('modelforms/author/<int:author_id>/', views.modelformsauthor, name="modelformauthor"),
    path('modelforms/book/<int:book_id>/', views.modelformbook, name="modelformbook"),
    path('customforms/', views.customforms, name='customforms'),
    path('formsets/', views.setforms, name='setforms'),
    path('modelformsets/', views.setmodelforms, name='setmodelforms'),
    path('inlineformsets/', views.inlineformset, name='inlineformset'),
    path('uploadfiles/', views.uploadfiles, name='uploadfiles'),
    path('uploadfilesmodel/', views.uploadfilesmodel, name='uploadfilesmodel'),
]

models/urls.py
from django.urls import path
from . import views

app_name = 'models'

urlpatterns = [
    path('', views.index, name='index')
]

forms/models.py
from django.db import models

TITLE_CHOICES = [
    ('MR', 'Mr.'),
    ('MRS', 'Mrs.'),
    ('MS', 'Ms.'),
]


# Create your models here.
class Upload(models.Model):
    name = models.CharField(max_length=100)
    upfile = models.FileField(upload_to='documents/')

    def __str__(self):
        return self.name


class Author(models.Model):
    name = models.CharField(max_length=100)
    title = models.CharField(max_length=3, choices=TITLE_CHOICES)
    birth_date = models.DateField(blank=True, null=True)

    def __str__(self):
        return self.name


class Book(models.Model):
    name = models.CharField(max_length=100)
    authors = models.ManyToManyField(Author)

    def __str__(self):
        return self.name


class BookForInline(models.Model):
    name = models.CharField(max_length=100)
    authors = models.ForeignKey(Author, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

models/apps.py
from django.apps import AppConfig


class ModelsConfig(AppConfig):
    name = 'models'

models/models.py
from django.db import models
# import datetime
from django.db.models import Count
from django.utils import timezone


# Create your models here.
class Person(models.Model):
    name = models.CharField(max_length=128)

    def __str__(self):
        return self.name


class Group(models.Model):
    name = models.CharField(max_length=128)
    members = models.ManyToManyField(Person, through='Membership')

    def get_absolute_url(self):
        return '/%s/' % self.name


class Membership(models.Model):
    person = models.ForeignKey(Person, on_delete=models.CASCADE)
    group = models.ForeignKey(Group, on_delete=models.CASCADE)
    date_joined = models.DateField()
    invite_reason = models.CharField(max_length=64)


"""Ниже другая группа моделей"""

class BlogManager(models.Manager):
    def my_create(self, *args, **kwards):
        print('Мы тут!')
        return super().create(*args, **kwards)

    """def get_queryset(self):
        return super().get_queryset().filter(name__contains='вариант')"""

    def with_counts(self):
        print('мы тут')
        return super().get_queryset().annotate(counts=Count('entry'))

    def short_list(self):
        return self.model.objects.all()[:4]
        # return super().get_queryset()[:3]


class Blog(models.Model):
    name = models.CharField(max_length=100)
    tagline = models.TextField()

    objects = BlogManager()

    def __str__(self):
        return self.name

    """def clean_fields(self, exclude=None):
        print("Клинфилдс")
        return super().clean_fields(exclude=exclude)

    def clean(self):
        print("Клин")
        return super().clean()"""

    @classmethod
    def createcls(cls, *args, **kwargs):
        print("Сработал классовый метод")
        return cls(*args, **kwargs)

    @property
    def myattr(self):
        return self.name, self.pk


class ThemeBlog(Blog):
    theme = models.CharField(max_length=200)


class Author(models.Model):
    name = models.CharField(max_length=100, db_index=True)
    email = models.EmailField()

    class Meta:
        #  тут можно и не составные индексы определять, походу самый удобный и наглядный способ.
        index_together = [
            ['name', 'email'],
            ['email'],
        ]

    def __str__(self):
        return self.name


class Entry(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    headline = models.CharField(max_length=255)
    text = models.TextField()
    pub_date = models.DateField(default=timezone.now)
    mod_date = models.DateTimeField(default=timezone.now)
    author = models.ManyToManyField(Author)
    number_of_comments = models.IntegerField(default=0)
    number_of_pingbacks = models.IntegerField(default=0)
    rating = models.IntegerField(default=0)

    def __str__(self):
        return self.headline

    def clean_fields(self, exclude=None):
        print("Клинфилдс")
        return super().clean_fields(exclude=exclude)

    def clean(self):
        print("Клин")
        return super().clean()

    def get_absolute_url(self):
        return '/' + self.headline + '/'

models/views.py
from django.shortcuts import render
from django.http import HttpResponse
from . import models

# Create your views here.
def index(request):
    from django.db.models import Prefetch

    """entrys = models.Entry.objects\
        .select_related('blog').prefetch_related('author')\
        .only('headline', 'blog__name', 'author__name')"""

    """entrys = models.Entry.objects\
        .select_related('blog')\
        .prefetch_related(Prefetch('author', queryset=models.Author.objects.only('name').order_by('-pk')))\
        .only('headline', 'blog__name')"""

    """entrys = models.Entry.objects\
        .select_related('blog')\
        .prefetch_related(
            Prefetch('author', to_attr='myattr'),
            Prefetch('author', queryset=models.Author.objects.order_by('-pk'), to_attr='rev'),
        )\
        .only('headline', 'blog__name')"""

    entrys = models.Entry.objects\
        .select_related('blog')\
        .prefetch_related(
            Prefetch('author', to_attr='myattr'),
        )\
        .only('headline', 'blog__name')


    # Если в запросе нет prefetch_relative, но есть select_relative - то его ОЧЕНЬ
    # удобно заменять  .values Это добавляет и JOIN и лучше всего ограничивает выборку полей одним махом
    # entrys = models.Entry.objects.values('headline', 'blog__name')
    # почти аналогично
    # (только две небольших разницы:
    # 1. в шаблоне отображения, blog__name и blog.name)
    # 2. два лишних поля по сравнению с values()
    # entrys = models.Entry.objects.select_related('blog').only('headline', 'blog__name')

    blogs = models.Blog.objects.prefetch_related(
        Prefetch('entry_set__author', to_attr='authors'),
    )

    authors = models.Author.objects.prefetch_related('entry_set__blog')

    context = {'entrys': entrys, 'blogs': blogs, 'authors': authors}
    return render(request, 'models/index.html', context)

myauth/models.py
from django.db import models

tools/models.py
from django.db import models
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation
from django.db import models
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth.models import User


# Create your models here.
class TaggedItem(models.Model):
    tag = models.SlugField()

    # три обязательных поля для обобщенной связи
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id', for_concrete_model=False)

    def __str__(self):
        return self.tag


class MyUser(User):
    tags = GenericRelation(TaggedItem, for_concrete_model=False)

    class Meta:
        proxy = True

models/templates/models/index.html
{% extends 'base.html' %}
{% block title %}Models{% endblock %}
{% block content %}
    {% comment %}
    <div class="row">
        <div class="col-sm-12">
            <h1>Authors</h1>
            <ul>
            {% for author in authors %}
                <li>
                    <h2>{{ author.name }}</h2>
                    <h4>Entrys:</h4>
                    <ul>
                    {% for entry in author.entry_set.all %}
                        <li>
                            {{ entry.headline }}
                            <h4>Blogs:</h4>
                            <ul>
                                <li>{{ entry.blog.name }}</li>
                            </ul>


                        </li>
                    {% endfor %}
                    </ul>
                </li>
            {% endfor %}
            </ul>
        </div>
    </div>
    {% endcomment %}
    {% comment %}
    <div class="row">
        <div class="col-sm-12">
            <h1>Blogs</h1>
            <ul>
                {% for blog in blogs %}
                <li>
                    <h2>{{ blog.name }}</h2>
                    <h4>Entrys:</h4>
                    <ul>
                        {% for entry in blog.entry_set.all %}
                        <li>
                            {{ entry.headline }}
                            <h4>Authors:</h4>
                            <ul>
                                {% for author in entry.authors %}
                                <li>{{ author.name }}</li>
                                {% endfor %}
                            </ul>
                        </li>
                        {% endfor %}
                    </ul>
                </li>
                {% endfor %}
            </ul>

        </div>
    </div>
    <hr>
    {% endcomment %}

    <div class="row">
    <div class="col-sm-12">
        <h1>Entrys:</h1>
        <ul>
            {% for item in entrys %}
            <li>
                <h2>{{ item.headline }}</h2>
                <p>{{ item.mod_date }}</p>
                <h4>Blogs</h4>
                <ul>
                    <li>{{ item.blog.name }}</li>
                </ul>
                <h4>Authors</h4>
                <ul>
                    {# for a in item.author.all #}
                    {% for a in item.myattr %}
                        <li>{{ a.name }}</li>
                    {% endfor %}
                    {% comment %}
                    <li><hr></li>
                    {% for a in item.rev %}
                        <li>{{ a.name }}</li>
                    {% endfor %}
                    {% endcomment %}
                </ul>
            </li>
            {% endfor %}
        </ul>

    </div>
</div>

{% endblock %}