djangobrief/urls.py
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.contrib.sitemaps.views import index # для индексного sitemap
from django.contrib.sitemaps import Sitemap
from models.models import Entry

from django.urls import path, include, reverse


# для media files
from django.conf.urls.static import static
from django.conf import settings
# для media files конец

from django.http import HttpResponse

# from django.contrib.flatpages import views

handler403 = 'template.views.response_error_handler'
handler404 = lambda request, exception: HttpResponse('привет. я handler404 in urls.py')


class BlogSitemap(Sitemap):
    changefreq = "never"
    priority = 0.5

    def items(self):
        return Entry.objects.all()

    def lastmod(self, obj):
        return obj.pub_date


class StaticSitemap(Sitemap):
    changefreq = 'never'
    priority = 0.6

    def items(self):
        return ['request:index', 'models:index']

    def location(self, obj):
        return reverse(obj)


sitemaps = {
    'entry': BlogSitemap,
    'static': StaticSitemap,
}

urlpatterns = [
    path('sitemap.xml', index, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.index'),
    path('sitemap-<section>.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('request/', include('request.urls')),
    path('forms/', include('forms.urls')),
    path('models/', include('models.urls')),
    path('template/', include('template.urls')),
    path('views/', include('views.urls')),
    path('myauth/', include('myauth.urls')),
    path('tools/', include('tools.urls')),
    path('admin/', admin.site.urls),
]

# для отображения media files
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += [
    path('', include('django.contrib.flatpages.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

forms/urls.py
from django.urls import path
from . import views


app_name = 'forms'

urlpatterns = [
    path('usualforms/', views.usualforms, name='usualforms'),
    path('modelforms/', views.modelforms, name="modelforms"),
    path('modelforms/author/<int:author_id>/', views.modelformsauthor, name="modelformauthor"),
    path('modelforms/book/<int:book_id>/', views.modelformbook, name="modelformbook"),
    path('customforms/', views.customforms, name='customforms'),
    path('formsets/', views.setforms, name='setforms'),
    path('modelformsets/', views.setmodelforms, name='setmodelforms'),
    path('inlineformsets/', views.inlineformset, name='inlineformset'),
    path('uploadfiles/', views.uploadfiles, name='uploadfiles'),
    path('uploadfilesmodel/', views.uploadfilesmodel, name='uploadfilesmodel'),
]

myauth/urls.py
from django.urls import path, include, reverse_lazy
from . import views
from django.contrib.auth import views as auth_views


app_name = 'myauth'
urlpatterns = [
    path('user/', views.user_actions, name='user_actions'),
    path('authenticate/', views.user_authenticate, name='user_authenticate'),
    path('registration/', views.MyUserRegistration.as_view(), name='user_registration'),
    path('registration2/', views.MyUserRegistration2.as_view(), name='user_registration2'),
    path('logout_func/', views.logout_view, name='logout_func'),
    path('simple/', views.simple_authenticate, name='simple_authenticate'),
    path('decorator/', views.decorator_authenticate, name='decorator_authenticate'),
    path('mixin/', views.MixinAuthenticate.as_view(), name='mixin_authenticate'),
    path('loginview/', views.MyLoginView.as_view(), name='loginview'),
    path('', include('django.contrib.auth.urls')),
    path('password-change/', auth_views.PasswordChangeView.as_view(
        success_url=reverse_lazy('myauth:password_change_done')), name='password_change'
         ),
]

template/urls.py
from django.urls import path
from . import views
from django.http import HttpResponse


app_name = 'template'
urlpatterns = [
    path('', views.index, name='index'),
]

tools/urls.py
from django.urls import path
from . import views


app_name = 'tools'
urlpatterns = [
    path('messages/', views.messages_view, name='messages_view'),
    path('xml/', views.xml_serialize_view, name='xml_serialize_view'),
    path('json/', views.json_serialize_view, name='json_serialize_view'),
    path('serialize-deserialize/', views.serialize_deserialize_view, name='serialize_deserialize_view'),
    path('sessions/', views.sessions_view, name='sessions_view'),
    path('static/', views.static_view, name='static_view'),
    path('validators/', views.validators_view, name='validators_view'),
    path('contenttypes/', views.contenttypes_view, name='contenttypes_view'),
    path('signals/', views.signals_view, name="signals_view"),
    path('sites/', views.sites_view, name='sites_view'),
]

views/urls.py
from django.urls import path
from . import views


app_name = 'views'
urlpatterns = [
    path('templateresponse/', views.template_response, name='templateresponse'),
    path('classview/', views.ClassView.as_view(), name='classview'),
    path('classtemplateview/', views.ClassTemplateView.as_view(), name='classtemplateview'),
    path('classredirectview/', views.ClassRedirectView.as_view(), name='classredirectview'),
    path('classdetailview/', views.ClassDetailView.as_view(), {'ug': 11}, name='classdetailview'),
    path('classlistview/', views.ClassListView.as_view(), name='classlistview'),
    path('classformview/', views.ClassFormView.as_view(), name='classformview'),
    path('classcreateview/', views.ClassCreateView.as_view(), name='classcreateview'),
    path('classupdateview/', views.ClassUpdateView.as_view(), {'pk': 8}, name='classupdateview'),
    path('classdeleteview/', views.ClassDeleteView.as_view(), {'pk': 12}, name='classdeleteview'),
]

templates/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
          integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

</head>
<body style="padding-top: 4.5rem">
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
        <a class="navbar-brand" href="#">DjangoBrief</a>

        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item dropdown active">
                    <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="false">Forms</a>
                    <div class="dropdown-menu" aria-labelledby="dropdown01">
                        <a class="dropdown-item" href="{% url 'forms:usualforms' %}">Usual Forms</a>
                        <a class="dropdown-item" href="{% url 'forms:modelforms' %}">Model Forms</a>
                        <a class="dropdown-item" href="{% url 'forms:customforms' %}">Custom Forms & Fields</a>
                        <a class="dropdown-item" href="{% url 'forms:setforms' %}">Form Sets</a>
                        <a class="dropdown-item" href="{% url 'forms:setmodelforms' %}">Model Form Sets</a>
                        <a class="dropdown-item" href="{% url 'forms:inlineformset' %}">Inline Form Sets</a>
                        <a class="dropdown-item" href="{% url 'forms:uploadfiles' %}">Upload Files</a>
                        <a class="dropdown-item" href="{% url 'forms:uploadfilesmodel' %}">Upload Files Model</a>
                    </div>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'request:index' %}">HttpRequest</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'models:index' %}">Models</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'template:index' %}">Templates</a>
                </li>
                <li class="nav-item dropdown active">
                    <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="false">Views</a>
                    <div class="dropdown-menu" aria-labelledby="dropdown01">
                        <a class="dropdown-item" href="{% url 'views:templateresponse' %}">TemplateResponse</a>
                        <a class="dropdown-item" href="{% url 'views:classview' %}">View</a>
                        <a class="dropdown-item" href="{% url 'views:classtemplateview' %}">TemplateView</a>
                        <a class="dropdown-item" href="{% url 'views:classredirectview' %}">RedirectView</a>
                        <a class="dropdown-item" href="{% url 'views:classdetailview' %}">DetailView</a>
                        <a class="dropdown-item" href="{% url 'views:classlistview' %}">ListView</a>
                        <a class="dropdown-item" href="{% url 'views:classformview' %}">FormView</a>
                        <a class="dropdown-item" href="{% url 'views:classcreateview' %}">CreateView</a>
                        <a class="dropdown-item" href="{% url 'views:classupdateview' %}">UpdateView</a>
                        <a class="dropdown-item" href="{% url 'views:classdeleteview' %}">DeleteView</a>
                    </div>
                </li>
                <li class="nav-item dropdown active">
                    <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="false">MyAuth</a>
                    <div class="dropdown-menu" aria-labelledby="dropdown01">
                        <a class="dropdown-item" href="{% url 'myauth:user_actions' %}">User Actions</a>
                        <a class="dropdown-item" href="{% url 'myauth:user_authenticate' %}">User Authenticate</a>
                        <a class="dropdown-item" href="{% url 'myauth:user_registration' %}">User Registration</a>
                        <a class="dropdown-item" href="{% url 'myauth:user_registration2' %}">User Registration2</a>
                        <hr>
                        <a class="dropdown-item" href="{% url 'myauth:simple_authenticate' %}">Simple Authenticate</a>
                        <a class="dropdown-item" href="{% url 'myauth:decorator_authenticate' %}">Decorator Authenticate</a>
                        <a class="dropdown-item" href="{% url 'myauth:mixin_authenticate' %}">Mixin Authenticate</a>
                        <hr>
                        <a class="dropdown-item" href="{% url 'myauth:loginview' %}">LoginView</a>
                        <hr>
                        <a class="dropdown-item" href="{% url 'myauth:login' %}">login</a>
                        <a class="dropdown-item" href="{% url 'myauth:logout' %}">logout</a>
                        <a class="dropdown-item" href="{% url 'myauth:password_change' %}">password_change</a>
                        <a class="dropdown-item" href="{% url 'myauth:password_change_done' %}">password_change_done</a>
                        <a class="dropdown-item" href="{% url 'myauth:password_reset' %}">password_reset</a>
                        <a class="dropdown-item" href="{% url 'myauth:password_reset_done' %}">password_reset_done</a>
                    </div>
                </li>
                <li class="nav-item dropdown active">
                    <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="false">Some Tools</a>
                    <div class="dropdown-menu" aria-labelledby="dropdown01">
                        <a class="dropdown-item" href="{% url 'tools:messages_view' %}">Flash message</a>
                        <a class="dropdown-item" href="{% url 'tools:xml_serialize_view' %}">XML-serialize</a>
                        <a class="dropdown-item" href="{% url 'tools:json_serialize_view' %}">JSON-serialize</a>
                        <a class="dropdown-item" href="{% url 'tools:serialize_deserialize_view' %}">
                            Serialize -> Deserialize
                        </a>
                        <a class="dropdown-item" href="{% url 'tools:sessions_view' %}">Sessions</a>
                        <a class="dropdown-item" href="{% url 'django.contrib.sitemaps.views.index' %}">Sitemap</a>
                        <a class="dropdown-item" href="{% url 'tools:static_view' %}">Static Files</a>
                        <a class="dropdown-item" href="{% url 'tools:validators_view' %}">Validators</a>
                        <a class="dropdown-item" href="{% url 'tools:contenttypes_view' %}">ContentTypes</a>
                        <hr>
                        {% load flatpages %}
                        {% get_flatpages as flatpages %}
                        {% for page in flatpages %}
                        <a class="dropdown-item" href="{{ page.url }}">{{ page.title }}</a>
                        {% endfor %}
                        <hr>
                        <a class="dropdown-item" href="/remote_url_for_redirect/">/remote_url_for_redirect/ (in BD)</a>
                        <a class="dropdown-item" href="{% url 'tools:signals_view' %}">Signals</a>
                        <a class="dropdown-item" href="{% url 'tools:sites_view' %}">Sites</a>
                    </div>
                </li>

            </ul>
        </div>
    </nav>

    <div role="main" class="container clearfix">{% block content %}{% endblock %}</div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

</body>
</html>