djangobrief/urls.py
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.contrib.sitemaps.views import index # для индексного sitemap
from django.contrib.sitemaps import Sitemap
from models.models import Entry

from django.urls import path, include, reverse


# для media files
from django.conf.urls.static import static
from django.conf import settings
# для media files конец

from django.http import HttpResponse

# from django.contrib.flatpages import views

handler403 = 'template.views.response_error_handler'
handler404 = lambda request, exception: HttpResponse('привет. я handler404 in urls.py')


class BlogSitemap(Sitemap):
    changefreq = "never"
    priority = 0.5

    def items(self):
        return Entry.objects.all()

    def lastmod(self, obj):
        return obj.pub_date


class StaticSitemap(Sitemap):
    changefreq = 'never'
    priority = 0.6

    def items(self):
        return ['request:index', 'models:index']

    def location(self, obj):
        return reverse(obj)


sitemaps = {
    'entry': BlogSitemap,
    'static': StaticSitemap,
}

urlpatterns = [
    path('sitemap.xml', index, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.index'),
    path('sitemap-<section>.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('request/', include('request.urls')),
    path('forms/', include('forms.urls')),
    path('models/', include('models.urls')),
    path('template/', include('template.urls')),
    path('views/', include('views.urls')),
    path('myauth/', include('myauth.urls')),
    path('tools/', include('tools.urls')),
    path('admin/', admin.site.urls),
]

# для отображения media files
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += [
    path('', include('django.contrib.flatpages.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

forms/urls.py
from django.urls import path
from . import views


app_name = 'forms'

urlpatterns = [
    path('usualforms/', views.usualforms, name='usualforms'),
    path('modelforms/', views.modelforms, name="modelforms"),
    path('modelforms/author/<int:author_id>/', views.modelformsauthor, name="modelformauthor"),
    path('modelforms/book/<int:book_id>/', views.modelformbook, name="modelformbook"),
    path('customforms/', views.customforms, name='customforms'),
    path('formsets/', views.setforms, name='setforms'),
    path('modelformsets/', views.setmodelforms, name='setmodelforms'),
    path('inlineformsets/', views.inlineformset, name='inlineformset'),
    path('uploadfiles/', views.uploadfiles, name='uploadfiles'),
    path('uploadfilesmodel/', views.uploadfilesmodel, name='uploadfilesmodel'),
]

models/urls.py
from django.urls import path
from . import views

app_name = 'models'

urlpatterns = [
    path('', views.index, name='index')
]

models/apps.py
from django.apps import AppConfig


class ModelsConfig(AppConfig):
    name = 'models'

myauth/models.py
from django.db import models

forms/apps.py
from django.apps import AppConfig


class FormsConfig(AppConfig):
    name = 'forms'

forms/forms.py
from django import forms
# import datetime
from django.utils import timezone
from . import models
from django.core.exceptions import ValidationError
from django.utils.translation import gettext as _
from django.core.validators import validate_email


class UploadFileModel(forms.ModelForm):
    class Meta:
        model = models.Upload
        fields = ['name', 'upfile']


class UploadFile(forms.Form):
    name = forms.CharField(max_length=100)
    upfile = forms.FileField(label='FileField')


# создаем свое поле, принимающее несколько значений емейл разделенных запятой
class MultiEmailField(forms.Field):

    widget = forms.Textarea(attrs={'rows': 3, 'cols': 55})

    def to_python(self, value):
        # raise ValidationError('to_python!')
        if not value:
            return []
        return value.split(',')

    def validate(self, value):
        # raise ValidationError('validate!')
        super().validate(value)
        for item in value:
            # print(item.strip())
            validate_email(item.strip())


class ContactForm(forms.Form):
    multiemail = MultiEmailField(help_text='Принимает несколько emeil через запятую')
    name = forms.CharField(required=False)
    datetimefield = forms.DateTimeField(label="DateTimeField",
                                        widget=forms.TextInput(attrs={
                                            'class': 'special',
                                            'type': 'datetime-local'
                                        }),
                                        initial=timezone.now,
                                        help_text='datetime-local Bootstrap 4'
                                        )

    def clean_multiemail(self):
        data = self.cleaned_data['multiemail']
        for i in data:
            if i == 'grecha@list.ru':
                raise ValidationError(
                    _('Invalid value: %(value)s'),
                    code='invalid',
                    params={'value': '43'},
            )
        return data

    """def clean(self):
        super().clean()
        data = self.cleaned_data.get('multiemail')
        # raise ValidationError(data)
        # self.add_error('multiemail', data)
        """




class AuthorForm(forms.ModelForm):
    prefix = 'author'

    # собственная проверка поля name
    """def clean_name(self):
        # print('aaaaa')
        name = self.cleaned_data['name']
        if name == '123':
            raise ValidationError("Имя не может быть 123!")
        return name

    def clean_name(self):  # здесь делаем проверку, для одного поля (здесь - name)
        raise ValidationError(
                    _('Invalid value: %(value)s'),
                    code='invalid',
                    params={'value': '42'},
            )

    def clean(self):  # в этом методе делаем проверку если она учитывает значения из нескольких полей
        raise ValidationError("clean!")"""

    class Meta:
        model = models.Author
        fields = ['name', 'title', 'birth_date']
        # exclude = ['name']
        widgets = {
            'name': forms.Textarea(attrs={'cols': 25, 'rows': 2})
        }


"""можно наследовать форму и переопределить проверку в ней. но зачем - не понятно
ибо работает и при переопределении в исходной форме"""
"""class AuthorFormMore(AuthorForm):
    # собственная проверку поля name
    def clean_name(self):
        print('aaaaa')
        name = self.cleaned_data['name']
        if name == '123':
            raise ValidationError("Имя не может быть 123!")

        return name"""


class BookForm(forms.ModelForm):
    prefix = 'book'
    class Meta:
        model = models.Book
        fields = ['name', 'authors']



class UsualForm(forms.Form):
    """по умолчанию эти две настройки (почти) нормально работают только в .as_table()
    но если форму вывожу в шаблон поэлементно - то в нужном месте можно вставить
    item.css_classes и тогда в этом месте будут классы в соответсвии с этими настройками"""
    error_css_class = "error123"  # работает в контейнере
    required_css_class = "field123"  # работает в элементе

    booleanfield = forms.BooleanField(required=False, label="BooleanField")
    charfield = forms.CharField(max_length=5, label="CharField", required=True,
                                widget=forms.TextInput(attrs={'class': 'anna'}))

    YEAR_IN_SCHOOL_CHOICES = [
        ('FR', 'Freshman'),
        ('SO', 'Sophomore'),
        ('JR', 'Junior'),
        ('SR', 'Senior'),
        ('GR', 'Graduate'),
    ]
    choicefield = forms.ChoiceField(choices=YEAR_IN_SCHOOL_CHOICES, label="ChoiceField")

    typedchoicefield = forms.TypedChoiceField(choices=YEAR_IN_SCHOOL_CHOICES, coerce=str, label="TypedChoiceField")
    datefield = forms.DateField(initial=timezone.now, label="DateField")
    datetimefield = forms.DateTimeField(initial=timezone.now, label="DateTimeField")
    decimalfield = forms.DecimalField(required=True, max_digits=4, decimal_places=2, label='DecimalField',
                                      error_messages={'max_digits': 'Слишком много цифр!'})
    durationfield = forms.DurationField(required=False, label="")
    emailfield = forms.EmailField(required=False, label="DurationField")
    # filefield = forms.FileField(label="FileField")
    # filepathfield = forms.FilePathField(label="FilePathField")
    floatfield = forms.FloatField(required=False, label="FloatField")
    # imagefield = forms.ImageField(label="ImageField")
    integerfield = forms.IntegerField(required=False, label="IntegerField")
    genericipaddresfield = forms.GenericIPAddressField(required=False, label="GenericIPAddressField")
    multiplechoicefield = forms.MultipleChoiceField(choices=YEAR_IN_SCHOOL_CHOICES, required=False,
                                                    label="MultipleChoiceField")
    typedmultiplechoicefield = forms.TypedMultipleChoiceField(choices=YEAR_IN_SCHOOL_CHOICES,
                                                              required=False, coerce=str,
                                                              label="TypedMultipleChoiceField")
    nullbooleanfield = forms.NullBooleanField(label="NullBooleanField")
    # regexfield = forms.RegexField(label="RegexField")
    slugfield = forms.SlugField(required=False, allow_unicode=True, label="SlugField")
    timefield = forms.TimeField(initial=timezone.now, label="TimeField")
    urlfield = forms.URLField(required=False, label="URLField")
    uuidfield = forms.UUIDField(required=False, label="UUIDField")

    # Достаточно сложные встроенные классы Field
    combofield = forms.ComboField(help_text='валидируется по нескольким полям', required=False, label="ComboField",
                                  fields=[forms.CharField(max_length=10), forms.EmailField()])
    # multivaluefield = forms.MultiValueField(label="MultiValueField")

    splitdatetimefield = forms.SplitDateTimeField(initial=timezone.now, label="SplitDateTimeField")

    # Поля для обработки связей
    # modelchoicefield = forms.ModelChoiceField(label="ModelChoiceField")
    # modelmultiplechoicefield = forms.ModelMultipleChoiceField(label="ModelMultipleChoiceField")

    # Создание собственных полей в customforms

forms/views.py
from django.shortcuts import render, redirect
from . import forms
from django.http import HttpResponse
from . import models
from django.forms import modelform_factory, formset_factory, modelformset_factory, inlineformset_factory
from django.core.files.storage import FileSystemStorage, get_storage_class


# Create your views here.
def uploadfilesmodel(request):
    if request.method == 'POST':
        form = forms.UploadFileModel(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('forms:uploadfilesmodel')
    else:
        form = forms.UploadFileModel()

    uploadfiles = models.Upload.objects.all()
    context = {'form': form, 'uploadfiles': uploadfiles}

    """Для удаления загруженного файла
    a = Upload.objects.get(pk=2)
    a.upfile.delete()
    a.delete()
    """

    """Для отображения media files внести изменения в urls.py"""

    return render(request, 'forms/uploadfilesmodel.html', context)



def uploadfiles(request):
    class Item:
        def __init__(self, name):
            self.name = name

        def __str__(self):
            return self.name

    if request.method == 'POST':
        form = forms.UploadFile(request.POST, request.FILES)
        form.is_valid()
        upfile = form.cleaned_data['upfile']
        cdata = []
        for x in dir(upfile):
            if not (x.startswith("_") or x == 'close' or x =='encoding' or x == 'fileno' or x == 'newlines'):
                i = Item(x)
                i.value = getattr(upfile, x, None)
                cdata.append(i)

        fs = FileSystemStorage()
        filename = fs.save(upfile.name, upfile)
        uploaded_file_url = fs.url(filename)
        # print(uploaded_file_url)
        i = Item('uploaded_file_url')
        i.value = uploaded_file_url
        cdata.append(i)
    else:
        form = forms.UploadFile()
        cdata = None


    context = {'form': form, 'cdata': cdata}

    return render(request, 'forms/uploadfiles.html', context)

def inlineformset(request):
    BookFormSet = inlineformset_factory(models.Author, models.BookForInline, fields='__all__', extra=1)
    author = models.Author.objects.get(pk=1)

    if request.method == 'POST':
        formset = BookFormSet(request.POST, instance=author)
        if formset.is_valid():
            formset.save()
            return redirect('forms:inlineformset')
    else:
        formset = BookFormSet(instance=author)

    context = {'formset': formset}
    return render(request, 'forms/inlineformset.html', context)


def setmodelforms(request):
    AuthorFormSet = modelformset_factory(models.Author, fields='__all__', extra=1)

    class ThinAuthorFormSet(AuthorFormSet):
        def __init__(self, *args, **kwargs):
            super().__init__( *args, **kwargs)
            self.queryset = models.Author.objects.filter(name__startswith='С')


    # formset =AuthorFormSet(queryset=models.Author.objects.filter(name__startswith='С'))
    formset = ThinAuthorFormSet()
    context = {'formset': formset}
    return render(request, 'forms/setmodelform.html', context)


def setforms(request):
    """Создаем setform. Создается одной функцией"""
    ContactFormSet = formset_factory(forms.ContactForm, extra=2)
    if request.method == 'POST':
        formset = ContactFormSet(request.POST)
        if formset.is_valid():
            cleaned_data = formset.cleaned_data
            print(formset.cleaned_data)
        else:
            cleaned_data = None
    else:
        formset = ContactFormSet()
        cleaned_data = None

    context = {'formset': formset, 'cleaned_data': cleaned_data}
    return render(request, 'forms/setform.html', context)


def customforms(request):
    if request.method == 'POST':
        form = forms.ContactForm(request.POST)
    else:
        form = forms.ContactForm()

    context = {'form': form}
    return render(request, 'forms/customform.html', context)


def modelformsauthor(request, author_id):
    i = models.Author.objects.get(pk=author_id)
    if request.method == 'POST':
        authorform = forms.AuthorForm(request.POST, instance=i)
        if authorform.is_valid():
            authorform.save()
            return redirect('forms:modelforms')
    else:
        authorform = forms.AuthorForm(instance=i)

    context = {'form': authorform, 'author_id': author_id}
    return render(request, 'forms/modelformauthor.html', context)


def modelformbook(request, book_id):
    i = models.Book.objects.get(pk=book_id)
    if request.method == 'POST':
        bookform = forms.BookForm(request.POST, instance=i)
        if bookform.is_valid():
            bookform.save()
            return redirect('forms:modelforms')
    else:
        # bookform = forms.BookForm(instance=i)
        """А можно и создать форму функцией modelform_factory:
        сначала создаем класс формы, а потом экземпляр.
        так можно делать и в forms.py"""
        BookFormFromFunc = modelform_factory(models.Book, fields='__all__')
        bookform = BookFormFromFunc(instance=i)

    context = {'form': bookform, 'book_id': book_id}
    return render(request, 'forms/modelformbook.html', context)


def modelforms(request):

    if request.method == 'POST':
        if any([x.startswith('author-') for x in request.POST.keys()]):
            authorform = forms.AuthorForm(request.POST)

            """хоть save() и проверяет данные в момент сохранения, но при ошибке вызывает ValueError что вызывает 500
            перед сохранением проверять is_valid() что бы вызывалось ValidationError оно штатно обрабатывается"""
            if authorform.is_valid():
                # print(authorform.cleaned_data)
                # i = authorform.save(commit=False)
                # i.name = 'Валера'
                # print(authorform.cleaned_data)
                # i.save()
                # authorform.save_m2m()
                authorform.save()
                return redirect('forms:modelforms')

        else:
            authorform = forms.AuthorForm()

        if any([x.startswith('book-') for x in request.POST.keys()]):
            bookform = forms.BookForm(request.POST)
            if bookform.is_valid():
                bookform.save()
                return redirect('forms:modelforms')
        else:
            bookform = forms.BookForm()



    else:
        authorform = forms.AuthorForm()
        bookform = forms.BookForm()

    authors = models.Author.objects.all()
    books = models.Book.objects.all()

    context = {'authorform': authorform, 'bookform': bookform, 'authors': authors, 'books': books}
    return render(request, 'forms/modelform.html', context)




def usualforms(request):
    context = {}
    if request.method == 'POST':
        form = forms.UsualForm(request.POST)
        form.is_valid()
        for k in form.cleaned_data:
            form[k].myattr = form.cleaned_data[k]
    else:
        form = forms.UsualForm()

    context.update({'form': form})
    # print(context)
    return render(request, 'forms/usualform.html', context)

forms/templates/forms/customform.html
{% extends 'base.html' %}

{% block title %}Custom Forms & Fields{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-sm-12">
            <h1>Custom Forms & Fields</h1>
            <form action="{% url 'forms:customforms' %}" method="post">
                {% csrf_token %}
                <table class="table">
                    {{ form }}
                    <tr>
                        <td></td>
                        <td><input type="submit" value="OK"></td>
                    </tr>
                </table>
            </form>
        </div>
    </div>
{% endblock %}

forms/templates/forms/inlineformset.html
{% extends 'base.html' %}

{% block title %}Inline Form Sets{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-sm-12">
            <h1>Inline Form Sets</h1>
            <form action="{% url 'forms:inlineformset' %}" method="post">
                {% csrf_token %}
                <table class="table table-hover">
                    {{ formset }}
                    <tr>
                        <td></td>
                        <td><input type="submit" value="OK"></td>
                    </tr>
                </table>
            </form>
        </div>
    </div>
{% endblock %}

forms/templates/forms/modelform.html
{% extends 'base.html' %}

    {% block title %}Model Forms{% endblock %}

    {% block content %}
        <div class="row"><div class="col-sm-12">
            <h1>Model Forms (django.forms.ModelForm)</h1>
        </div></div>
        <div class="row">
            <div class="col-sm-6">
                <h2>AuthorForm</h2>
                <form method="post" action="{% url 'forms:modelforms' %}" id="form1">
                    {% csrf_token %}
                    <table class="table">
                        {{ authorform }}
                        <tr>
                            <td></td>
                            <td><input type="submit" value="OK"></td>
                        </tr>
                    </table>

                </form>
            </div>
            <div class="col-sm-6">
                <h2>BookForm</h2>
                <form method="post" action="{% url 'forms:modelforms' %}" id="form2">
                    {% csrf_token %}
                    <table class="table">
                        {{ bookform }}
                        <tr>
                            <td></td>
                            <td><input type="submit" value="OK"></td>
                        </tr>
                    </table>
                </form>
            </div>
        </div>
        <hr>
        <div class="row">
            <div class="col-sm-6">
                <h2>Authors</h2>
                <table class="table table-hover">
                    {% for item in authors %}
                        <tr>
                            <td>
                                <a href="{% url 'forms:modelformauthor' item.pk %}">{{ item.pk }}</a>
                            </td>
                            <td>{{ item.name }}</td>
                            <td>{{ item.title }}</td>
                            <td>{{ item.birth_date }}</td>
                        </tr>
                    {% endfor %}
                </table>
            </div>

            <div class="col-sm-6">
                <h2>Books</h2>
                <table class="table table-hover">
                    {% for item in books %}
                        <tr>
                            <td>
                                <a href="{% url 'forms:modelformbook' item.pk %}">{{ item.pk }}</a>
                            </td>
                            <td>{{ item.name }}</td>
                            <td>{{ item.authors }}</td>
                        </tr>
                    {% endfor %}
                </table>
            </div>
        </div>

    {% endblock %}

forms/templates/forms/modelformauthor.html
{% extends 'base.html' %}

{% block title %}Редактирование Author{% endblock %}

{% block content %}
<div class="row">
    <div class="col-row-12">
        <h1>Редактирование Author</h1>
        <form method="post" action="{% url 'forms:modelformauthor' author_id %}">
            {% csrf_token %}
             <table class="table">
                {{ form }}
            </table>
            <input type="submit" value="OK">
        </form>
    </div>
</div>
{% endblock %}

forms/templates/forms/modelformbook.html
{% extends 'base.html' %}

{% block title %}Редактирование Book{% endblock %}

{% block content %}
<div class="row">
    <div class="col-row-12">
        <h1>Редактирование Book</h1>
        <form method="post" action="{% url 'forms:modelformbook' book_id %}">
            {% csrf_token %}
             <table class="table">
                {{ form }}
                 <tr>
                     <td></td>
                     <td><input type="submit" value="OK"></td>
                 </tr>
            </table>
        </form>
    </div>
</div>
{% endblock %}

forms/templates/forms/setform.html
{% extends 'base.html' %}

{% block title %}Form Sets{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-sm-12">
            <h1>Form Sets</h1>
            <form action="{% url 'forms:setforms' %}" method="post">
                {% csrf_token %}
                <table class="table">
                    {{ formset }}
                    <tr>
                        <td></td>
                        <td><input type="submit" value="OK"></td>
                    </tr>
                </table>
            </form>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <h2>Cleaned_data</h2>
            <table class="table table-hover">
            {% for i in cleaned_data %}
                <tr>
                    <td>{{ i.multiemail }}</td>
                    <td>{{ i.name }}</td>
                    <td>{{ i.datetimefield }}</td>
                </tr>
            {% endfor %}
            </table>
        </div>
    </div>
{% endblock %}

forms/templates/forms/setmodelform.html
{% extends 'base.html' %}

{% block title %}Model Form Sets{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-sm-12">
            <h2>Model Form Sets</h2>
            <form method="post" action="{% url 'forms:setmodelforms' %}">
                {% csrf_token %}
                <table class="table table-hover">
                    {{ formset }}
                    <tr>
                        <td></td>
                        <td><input type="submit" value="OK"></td>
                    </tr>
                </table>
            </form>
        </div>
    </div>
{% endblock %}

forms/templates/forms/uploadfiles.html
{% extends 'base.html' %}
{% block title %}Upload Files{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-sm-12">
            <h1>Upload Files</h1>
            <form action="{% url 'forms:uploadfiles' %}" method="post" enctype="multipart/form-data">
                {% csrf_token%}
                <table class="table">
                    {{ form }}
                    <tr>
                        <td></td>
                        <td><input type="submit" value="OK"></td>
                    </tr>
                </table>
            </form>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <h2>Cleaned_data File Object</h2>
            <p>close(), encoding, fileno, newlines</p>
            <table class="table table-hover">
                {% for item in cdata %}
                    <tr>
                        <td>{{ item }}</td>
                        <td>{{ item.value }}</td>
                    </tr>
                {% endfor %}
            </table>
            {# cdata.upfile.size #}
        </div>
    </div>
{% endblock %}

forms/templates/forms/uploadfilesmodel.html
{% extends 'base.html' %}
{% block title %}Upload Files Model{% endblock %}
{% block content %}
<div class="row">
    <div class="col-sm-12">
        <h1>Upload Files Model</h1>
        <form enctype="multipart/form-data" method="post" action="{% url 'forms:uploadfilesmodel' %}">
            {% csrf_token %}
            <table class="table">
                {{ form }}
                <tr>
                    <td></td>
                    <td>
                        <input type="submit" value="OK">
                    </td>
                </tr>
            </table>
        </form>
    </div>
</div>
<div class="row">
    <div class="col-sm-12">
        {% for item in uploadfiles %}
            <img src="/media/{{ item.upfile }}">
        {% endfor %}
    </div>
</div>
{% endblock %}

forms/templates/forms/usualform.html
{% extends 'base.html' %}
{% load tz %}
{% block title %}Usual Forms{% endblock %}
    {% block content %}
        <div class="row">
            <div class="col-sm-9">
                <h1>Usual Forms (django.forms.Form)</h1>
                <form method="post" action="{% url 'forms:usualforms' %}">
                    {% csrf_token %}
                    <table class="table table-hover">
                        <tr>
                            <th>Label</th>
                            <th>Field</th>
                            <th>Cleaned_data</th>
                        </tr>
                        {% for item in form %}
                        <tr>
                            <td class="{{ item.css_classes }}">{{ item.label_tag }}</td>
                            <td>
                                {% if item.errors %}
                                    {% for error in item.errors %}
                                        <p class="alert alert-danger">{{ error }}</p>
                                    {% endfor %}
                                {% endif %}

                                {{ item }}
                                {% if item.help_text %}
                                    <p>{{ item.help_text|safe }}</p>
                                {% endif %}
                            </td>
                            <td>
                                {{ item.myattr }}
                            </td>
                        </tr>
                        {% endfor %}
                        <tr>
                            <td></td>
                            <td colspan="2">
                                <input type="submit" value="OK">
                            </td>
                        </tr>
                    </table>
                </form>
            </div>

            <div class="col-sm-3">
                <h3>Аргументы поля</h3>
                <dl>
                    <dt>required</dt>
                    <dd>определение</dd>

                    <dt>label</dt>
                    <dd></dd>

                    <dt>label_suffix</dt>
                    <dd></dd>

                    <dt>initial</dt>
                    <dd></dd>

                    <dt>widget</dt>
                    <dd></dd>

                    <dt>help_text</dt>
                    <dd></dd>

                    <dt>error_messages={'required': 'Please enter your name'}</dt>
                    <dd></dd>

                    <dt>validators</dt>
                    <dd></dd>

                    <dt>localize</dt>
                    <dd></dd>

                    <dt>disabled</dt>
                    <dd></dd>

                    <dt>max_length</dt>
                    <dd></dd>

                    <dt>min_length</dt>
                    <dd></dd>

                    <dt>strip</dt>
                    <dd>обрезает пробелы в начале/конце</dd>

                    <dt>empty_value</dt>
                    <dd></dd>

                    <dt>choices</dt>
                    <dd></dd>

                    <dt>coerce</dt>
                    <dd>Функция, которая принимает один аргумент и возвращает преобразованное значение.
                        Преобразование происходит после валидации</dd>

                    <dt>input_formats</dt>
                    <dd></dd>

                    <dt>max_digits (для DecimalField)</dt>
                    <dd></dd>

                    <dt>decimal_places (аналогично)</dt>
                    <dd></dd>

                    <dt>path (для FilePathField)</dt>
                    <dd></dd>

                    <dt>recursive (аналогично)</dt>
                    <dd></dd>

                    <dt>match (аналогично, регулярка)</dt>
                    <dd></dd>

                    <dt>allow_files (аналогично)</dt>
                    <dd></dd>

                    <dt>allow_folders (аналогично)</dt>
                    <dd></dd>

                    <dt>protocol (для GenericIPAddressField)</dt>
                    <dd></dd>

                    <dt>unpack_ipv4 (аналогично)</dt>
                    <dd></dd>

                    <dt>regex (для RegexField)</dt>
                    <dd></dd>

                    <dt>allow_unicode (для SlugField)</dt>
                    <dd></dd>

                    <dt>fields (для ComboField, MultiValueField)</dt>
                    <dd></dd>

                    <dt>require_all_fields (для MultiValueField)</dt>
                    <dd></dd>

                    <dt>compress (аналогично)</dt>
                    <dd></dd>

                    <dt>input_date_formats (для SplitDateTimeField)</dt>
                    <dd></dd>

                    <dt>input_time_formats (аналогично)</dt>
                    <dd></dd>

                    <dt>queryset (для ModelChoiceField)</dt>
                    <dd></dd>

                    <dt>empty_label (аналогично)</dt>
                    <dd></dd>

                    <dt>to_field_name (аналогично)</dt>
                    <dd></dd>

                    <dt>Form.has_changed()</dt>
                    <dd></dd>

                    <dt>Field.clean(value)</dt>
                    <dd></dd>
                </dl>
            </div>
        </div>
    {% endblock %}